Repository Edwardb11/budget-app, pull requests merged in 2022-04, with the labels that each got.

#4 PWA
  .gitignore
  assets/favicon.ico
  index.html
  manifest.json
  package-lock.json
  package.json
  src/ReloadPrompt.css
  src/ReloadPrompt.jsx
  src/favicon.ico
  src/favicon.svg
  src/main.jsx
  vite.config.js
Labels: documentation, enhancement

#3 feature - husky
  .husky/pre-commit
  package-lock.json
  package.json
Labels: enhancement, help wanted

#10 Add project configuration
  .editorconfig
  .eslintrc.json
  .husky/pre-commit
  .prettierrc.json
  .vscode/settings.json
  CONTRIBUTING.md
  LICENSE
  README.md
  SECURITY.md
  docs/README.md
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.jsx
  src/App.tsx
  src/assets/favicon.ico
  src/components/footer/index.tsx
  src/components/header/index.tsx
  src/components/index.ts
  src/components/reload-prompt/index.tsx
  src/components/reload-prompt/styles.css
  src/favicon.ico
  src/hooks/app-recoil.ts
  src/index.css
  src/interfaces/index.d.ts
  src/logo.svg
  src/main.jsx
  src/main.tsx
  src/routes/about.tsx
  src/routes/home.tsx
  src/routes/index.ts
  src/routes/layout.tsx
  src/routes/no-match.tsx
  src/services/index.ts
  src/theme.ts
  src/utils/index.ts
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: enhancement
